name: single-screenshot

on: workflow_dispatch

jobs:
  screenshot:
    name: 'take screenshot'
    runs-on: ubuntu-latest

    steps:
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://mdsinabox.com/nba/
        destination: screenshot.png
        full-page: true
        width: 720